language: python
python:
  - "3.6"

install:
  - python3.6 -m pip install flake8
  - cd src
  - python3.6 -m pip install -t vendored -r requirements.txt
  - cd ..

script:
  - cd src
  - python3.6 -m flake8 -v
