AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Nysseituu

Resources:
  NysseituuFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python2.7
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          TWEETING_ALLOWED: "False"
  Table:
    Type: AWS::Serverless::SimpleTable
