service: nysseituu

custom:
  region: eu-west-1
  tableName: ${self:service}
  secret: ${file(../secrets.yml)}

provider:
  name: aws
  runtime: python3.6
  region: ${self:custom.region}
  profile: heap
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.tableName}"
  environment:
    NYSSEITUU_TABLE_NAME: ${self:custom.tableName}
    TWITTER_CONSUMER_KEY: ${self:custom.secret.twitter_consumer_key}
    TWITTER_CONSUMER_SECRET: ${self:custom.secret.twitter_consumer_secret}
    TWITTER_TOKEN_KEY: ${self:custom.secret.twitter_token_key}
    TWITTER_TOKEN_SECRET: ${self:custom.secret.twitter_token_secret}
    TWEETING_ALLOWED: "false"
    IN_AWS: "true"

package:
  exclude:
    - "*.txt"
    - "*.md"
    - ".flake8"

functions:
  nysseituu:
    handler: main.handler
    memorySize: 256
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
